# Generated by Django 4.1.3 on 2022-11-19 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_type_alter_product_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Type',
            new_name='Product_Type',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='type',
            new_name='product_type',
        ),
    ]
