# Generated by Django 4.1.3 on 2022-11-19 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0003_rename_type_product_type_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product_Type',
            new_name='Type',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_type',
            new_name='type',
        ),
    ]
